image: jackfirth/racket:7.2

test:
  before_script:
    - apt-get update && apt-get install -y libgccjit-6-dev
    - dpkg-query -L libgccjit-6-dev
    - export LD_LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/6/:$LD_LIBRARY_PATH
  script:
    - racket test/hello-world.rkt > file
    - echo 'hello world' > expected
    - cmp --silent expected file
